services:
  mysql:
    image: mysql:8.0
    container_name: campusbite_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: campusbite
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
